Repository TilsynForUniversellUtforming/testreglar-wcag-2.x, pull requests merged in 2023-10, with the labels that each got.

#215 Create dependabot.yml
  .github/dependabot.yml
Labels: dependencies

#204 app-3.3.1b er klar for ks
  Testreglar/3.3.1/App/app-3.3.1b.json
Labels: Kvalitetssikring er gjennomført

#225 Oppdatert dokumentasjon
  Doc/Testregelformat/Testregelformat.md
  Utdatert/1.4.1/Nett/1.4.1a.json
  Utdatert/1.4.1/Nett/1.4.1b.json
  Utdatert/1.4.1/Nett/1.4.1c.json
Labels: documentation
