Repository TilsynForUniversellUtforming/testreglar-wcag-2.x, pull requests merged in 2023-12, with the labels that each got.

#271 Testing: Bedre fangst og feilmelding av tomme testregel-filer
  Tests/format.test.ts
Labels: Forbedring

#207 nett-4.1.2a er klar for ks
  Testreglar/4.1.2/Nett/nett-4.1.2a.json
Labels: Kvalitetssikring er gjennomført

#251 nett-4.1.2d er klar for ks
  Testreglar/4.1.2/Nett/nett-4.1.2d.json
Labels: Kvalitetssikring er gjennomført

#231 app 1.4.4a JBK klar til ks
  Testreglar/1.4.4/App/app-144a.json
Labels: Kvalitetssikring er gjennomført

#234 Nett-2.1.1a Det er mogleg å nå innhald og bruke funksjonalitet med tastatur (2023)
  Testreglar/2.1.1/Nett/nett-2.1.1a.json
  Utdatert/2.1.1/2.1.1a.json
Labels: Kvalitetssikring er gjennomført

#233 App-2.1.1a-jbk-Det-er-mogleg-å-nå-innhald-og-bruke-funksjonalitet-med-sveiping-2023 Klar for KS
  Testreglar/2.1.1/App/app-2.1.1a.json
  Utdatert/2.1.1/app-2.1.1a.json
Labels: Kvalitetssikring er gjennomført

#235 Nett-2.4.7a Innhald som kan brukast med tastatur, får synleg fokusmarkering 2023 klar for KS.
  Testreglar/2.4.7/Nett/nett-2.4.7a.json
  Utdatert/2.4.7/2.4.7a.json
Labels: Kvalitetssikring er gjennomført

#240 Nett-2.1.2a Det finst ingen tastaturfelle på nettsida 2023 klar for KS.
  Testreglar/2.1.2/Nett/nett-2.1.2.json
  Utdatert/2.1.2/nett/2.1.2a.json
Labels: Kvalitetssikring er gjennomført

#241 app-2.1.2a Det finst ingen tastaturfelle på appsida 2023 klar for KS
  Testreglar/2.1.2/App/app-2.1.2a.json
  Utdatert/2.1.2/app/app-2.1.2a.json
Labels: Kvalitetssikring er gjennomført

#270 nett-1.1.1a er klar for ks
  Testreglar/1.1.1/Nett/nett-1.1.1a.json
Labels: Kvalitetssikring er gjennomført, Frist 15.12

#278 nett 1.1.1c er klar for ks
  Testreglar/1.1.1/Nett/nett-1.1.1c.json
Labels: Kvalitetssikring er gjennomført, Frist 15.12

#287 nett 2.4.6a er klar for ks
  Testreglar/2.4.6/Nett/nett-2.4.6a.json
Labels: Kvalitetssikring er gjennomført, Ferdig, Frist 22.12

#288 app 2.4.6a er klar for ks
  Testreglar/2.4.6/App/app-2.4.6a.json
Labels: Klar for kvalitetssikring, Kvalitetssikring er gjennomført, Ferdig, Frist 22.12

#291 nett 3.2.2a er klar for ks
  Testreglar/3.2.2/Nett/nett-3.2.2a.json
Labels: Kvalitetssikring er gjennomført, Frist 22.12

#281 nett 1.1.1d er klar for ks
  Testreglar/1.1.1/Nett/nett-1.1.1d.json
Labels: Kvalitetssikring er gjennomført, Frist 15.12
