Repository TilsynForUniversellUtforming/testreglar-wcag-2.x, pull requests merged in 2023-07, with the labels that each got.

#141 nett-4.1.3a er klar for KS
  Testreglar/413/App/.gitkeep
  Testreglar/413/Nett/.gitkeep
  Testreglar/413/Nett/nett-4.1.3a.json
Labels: Klar for kvalitetssikring

#152 Depend: Bump eslint til siste versjon
  package-lock.json
  package.json
Labels: dependencies

#153 Typescript
  .eslintrc.json
  .gitignore
  Doc/Testregelformat/Testregelformat.md
  Mal/mal.json
  README.md
  Tests/format.test.ts
  _config.yml
  jest.config.js
  obj/Release/testreglar-wcag-2.x.njsproj.AssemblyReference.cache
  package-lock.json
  package.json
  src/app.ts
  testreglar-wcag-2.x.njsproj
  testreglar-wcag-2.x.sln
  tsconfig.json
Labels: Forbedring

#154 fjerna cache
  obj/Release/testreglar-wcag-2.x.njsproj.AssemblyReference.cache
Labels: bug

#162 Oppdatert test
  Tests/format.test.ts
Labels: bug

#163 Lagt til flere tester
  Tests/format.test.ts
Labels: Forbedring
