Repository TilsynForUniversellUtforming/testreglar-wcag-2.x, pull requests merged in 2023-06, with the labels that each got.

#137 Oppdatert standardtekster for app
  Mal/standardtekstar.json
Labels: Klar for kvalitetssikring

#132 nett-2.5.1a er klar for KS
  Testreglar/251/Nett/nett-2.5.1a.json
Labels: Kvalitetssikring er gjennomført

#133 app-2.5.1a er klar for KS
  Testreglar/251/App/.gitkeep
  Testreglar/251/App/app-2.5.1a.json
  Testreglar/251/Nett/.gitkeep
Labels: Kvalitetssikring er gjennomført

#131 Fikser #130 app-1.3.4a mangler steg for å sjekke om innhold kan brukes
  Testreglar/134/App/app-1.3.4a.json
Labels: Forbedring, Kvalitetssikring er gjennomført

#128 nett-1.4.13b er klar for KS
  Testreglar/1413/Nett/nett-1.4.13b.json
Labels: Kvalitetssikring er gjennomført

#144 Skrivefeil app-1.4.11b.json
  Testreglar/1411/App/app-1.4.11b.json
Labels: bug

#145 Skrivefeil i nett-1.4.12a
  Testreglar/1412/Nett/nett-1.4.12a.json
Labels: bug, Kvalitetssikring er gjennomført

#129 nett-2.1.4a er klar for KS
  Testreglar/214/App/.gitkeep
  Testreglar/214/Nett/.gitkeep
  Testreglar/214/Nett/nett-2.1.4a.json
Labels: Må endres

#134 nett-2.5.2a er klar for KS
  Testreglar/252/App/.gitkeep
  Testreglar/252/Nett/.gitkeep
  Testreglar/252/Nett/nett-2.5.2a.json
Labels: Kvalitetssikring er gjennomført

#135 nett-2.5.3a er klar for KS
  Testreglar/253/App/.gitkeep
  Testreglar/253/Nett/.gitkeep
  Testreglar/253/Nett/nett-2.5.3a.json
Labels: Kvalitetssikring er gjennomført

#136 app-2.5.3a er klar for KS
  Testreglar/253/App/app-2.5.3a.json
Labels: Klar for kvalitetssikring

#139 app-2.5.2a er klar for KS
  Testreglar/252/App/app-2.5.2a.json
Labels: Kvalitetssikring er gjennomført

#140 app-2.5.4a er klar for KS
  Testreglar/254/App/app-2.5.4a.json
Labels: Kvalitetssikring er gjennomført

#138 nett-2.5.4a er klar for KS
  Testreglar/254/App/.gitkeep
  Testreglar/254/Nett/.gitkeep
  Testreglar/254/Nett/nett-2.5.4a.json
Labels: Kvalitetssikring er gjennomført

#150 Lagt inn nye standardtekster
  Mal/standardtekstar.json
Labels: Forbedring

#147 nett-1.2.5a er klar for KS
  Testreglar/125/App/.gitkeep
  Testreglar/125/Nett/.gitkeep
  Testreglar/125/Nett/nett-1.2.5a.json
Labels: Klar for kvalitetssikring

#148 app-1.2.5a er klar for KS
  Testreglar/125/App/app-1.2.5a.json
Labels: Klar for kvalitetssikring
