Repository TilsynForUniversellUtforming/testreglar-wcag-2.x, pull requests merged in 2024-03, with the labels that each got.

#441 nett-2.2.2a er klar for ks
  Testreglar/2.2.2/Nett/nett-2.2.2a.json
Labels: Kvalitetssikring er gjennomført, First 08.03

#477 Lagt til test av javascript
  Tests/format.test.ts
Labels: Forbedring

#349 nett 1.3.1a er klar for ks
  Testreglar/1.3.1/Nett/nett-1.3.1a.json
Labels: Kvalitetssikring er gjennomført, Frist 26.01

#417 nett-2.4.1a er klar for ks
  Testreglar/2.4.1/Nett/nett-2.4.1a.json
Labels: Kvalitetssikring er gjennomført, Frist 09.02

#424 nett-1.2.2a er klar for ks
  Testreglar/1.2.2/Nett/nett-1.2.2a.json
Labels: Kvalitetssikring er gjennomført, Frist 16.02

#426 app-1.2.2a er klar for ks
  Testreglar/1.2.2/App/app-1.2.2a.json
Labels: Kvalitetssikring er gjennomført, Frist 16.02

#480 nett-1.4.12a Fjernet javascript fra steg 3.3
  Testreglar/1.4.12/Nett/nett-1.4.12a.json
Labels: bug, Klar for kvalitetssikring, Frist 15.03

#439 nett-1.3.3a er klar for ks
  Testreglar/1.3.3/Nett/nett-1.3.3a.json
Labels: Kvalitetssikring er gjennomført, Frist 01.03

#440 app-1.3.3a er klar for ks
  Testreglar/1.3.3/App/app-1.3.3a.json
Labels: Kvalitetssikring er gjennomført, Frist 01.03

#442 nett-2.2.2b er klar for ks
  Testreglar/2.2.2/Nett/nett-2.2.2b.json
Labels: Kvalitetssikring er gjennomført, First 08.03

#459 Fjern "Det er flere måter å oppfylle kravet på" fra alle testregler
  Testreglar/1.3.4/App/app-1.3.4a.json
  Testreglar/1.4.12/Nett/nett-1.4.12a.json
  Testreglar/4.1.2/Nett/nett-4.1.2a.json
Labels: Forbedring, Kvalitetssikring er gjennomført, Frist 15.03

#476 nett-2.2.2a Krav til samsvar har blitt oppdatert
  Testreglar/2.2.2/Nett/nett-2.2.2a.json
Labels: bug, Kvalitetssikring er gjennomført, Frist 15.03

#443 app-2.2.2a er klar for ks
  Testreglar/2.2.2/App/app-2.2.2a.json
Labels: Kvalitetssikring er gjennomført, First 08.03

#444 app-2.2.2b er klar for ks
  Testreglar/2.2.2/App/app-2.2.2b.json
Labels: Kvalitetssikring er gjennomført, First 08.03

#447 app-1.4.2a er klar for ks
  Testreglar/1.4.2/App/app-1.4.2a.json
Labels: Kvalitetssikring er gjennomført, First 08.03

#458 Endret begrep Accessibility Checker til Accessibility Tree i alle testregler
  Testreglar/1.1.1/Nett/nett-1.1.1a.json
  Testreglar/1.3.1/Nett/nett-1.3.1b.json
  Testreglar/1.3.1/Nett/nett-1.3.1c.json
  Testreglar/1.3.1/Nett/nett-1.3.1d.json
  Testreglar/1.3.1/Nett/nett-1.3.1e.json
  Testreglar/1.4.3/Nett/1.4.3c.json
  Testreglar/1.4.3/Nett/nett-1.4.3a.json
  Testreglar/4.1.2/Nett/nett-4.1.2a.json
  Testreglar/4.1.2/Nett/nett-4.1.2c.json
  Testreglar/4.1.2/Nett/nett-4.1.2d.json
Labels: Forbedring, Kvalitetssikring er gjennomført, Frist 15.03

#453 nett-2.2.1a er klar for ks
  Testreglar/2.2.1/Nett/nett-2.2.1a.json
Labels: Kvalitetssikring er gjennomført, Frist 15.03

#465 nett-1.2.1a er klar for ks
  Testreglar/1.2.1/Nett/1.2.1a.json
  Testreglar/1.2.1/Nett/1.2.1b.json
  Testreglar/1.2.1/Nett/nett-1.2.1a.json
Labels: Kvalitetssikring er gjennomført, Frist 22.03

#466 app-1.2.1a er klar for ks
  Testreglar/1.2.1/App/app-1.2.1a.json
Labels: Kvalitetssikring er gjennomført, Frist 22.03
