Repository TilsynForUniversellUtforming/testreglar-wcag-2.x, pull requests merged in 2024-01, with the labels that each got.

#308 Testregelformat - Fjernet Kolonner
  Doc/Testregelformat/Testregelformat.md
  Tests/format.test.ts
Labels: Forbedring, Ferdig

#342 Bug: Lagt til manglende delutfall for steg 3.9
  Testreglar/1.3.1/Nett/1.3.1b.json
Labels: bug

#347 Oppdatert workflow til Node v20
  .github/workflows/main.yml
Labels: dependencies

#209 nett-4.1.2b er klar for ks
  Testreglar/4.1.2/Nett/nett-4.1.2b.json
Labels: Kvalitetssikring er gjennomført, Frist 15.12

#276 app 1.1.1a er klar for ks
  Testreglar/1.1.1/App/app-1.1.1a.json
  Utdatert/1.1.1/App/app-1.1.1a-2022.json
Labels: Kvalitetssikring er gjennomført, Frist 15.12

#277 nett 1.1.1b er klar for ks
  Testreglar/1.1.1/Nett/nett-1.1.1b.json
Labels: Kvalitetssikring er gjennomført, Frist 15.12

#285 app 3.3.2a er klar for ks
  Testreglar/3.3.2/App/app-3.3.2a.json
  Utdatert/3.3.2/App/app-3.3.2a-2022.json
Labels: Kvalitetssikring er gjennomført, Frist 15.12

#292 app 3.2.2a er klar for ks
  Testreglar/3.2.2/App/app-3.2.2a.json
Labels: Kvalitetssikring er gjennomført, Frist 22.12

#293 nett 2.4.3a er klar for ks
  Testreglar/2.4.3/Nett/nett-2.4.3a.json
Labels: Kvalitetssikring er gjennomført, Frist 22.12

#294 nett 2.4.2a er klar for ks
  Testreglar/2.4.2/Nett/nett-2.4.2a.json
Labels: Kvalitetssikring er gjennomført, Frist 22.12

#299 app 2.4.4a er klar for ks
  Testreglar/2.4.4/App/app-2.4.4a.json
Labels: Kvalitetssikring er gjennomført, Frist 22.12

#310 nett 3.2.1a er klar for ks
  Testreglar/3.2.1/Nett/nett-3.2.1a.json
Labels: Kvalitetssikring er gjennomført, Frist 12.01

#366 Dokumentasjon: Oppdatert dokumentasjon med delutfall
  Doc/Testregelformat/Testregelformat.md
Labels: documentation

#367 Oppdatert tester
  Tests/format.test.ts
Labels: Forbedring

#372 Bug: Manglende utfall #371
  Testreglar/1.1.1/Nett/1.1.1c.json
  Testreglar/1.1.1/Nett/nett-1.1.1c.json
  Testreglar/1.3.1/Nett/1.3.1a.json
  Testreglar/1.3.1/Nett/1.3.1c.json
  Testreglar/1.4.1/App/app-1.4.1a.json
Labels: bug, Klar for kvalitetssikring

#365 Bug: Manglende labels #363
  Testreglar/1.2.5/App/app-1.2.5a.json
  Testreglar/1.2.5/Nett/nett-1.2.5a.json
  Testreglar/1.3.5/App/app-1.3.5a.json
  Testreglar/1.4.10/App/app-1.4.10a.json
  Testreglar/1.4.10/Nett/nett-1.4.10a.json
Labels: bug, Klar for kvalitetssikring

#378 Added label.yml
  .github/workflows/label.yml
Labels: Forbedring

#309 nett 2.4.5a er klar for ks
  Testreglar/2.4.5/Nett/nett-2.4.5a.json
Labels: Kvalitetssikring er gjennomført, Frist 12.01

#313 nett 3.1.1a er klar for ks
  Testreglar/3.1.1/Nett/nett-3.1.1a.json
Labels: Kvalitetssikring er gjennomført, Frist 12.01

#314 app-3.1.1a er klar for ks
  Testreglar/3.1.1/App/app-3.1.1a.json
Labels: Kvalitetssikring er gjennomført, Frist 12.01

#315 nett 3.1.2a er klar for ks
  Testreglar/3.1.2/Nett/nett-3.1.2a.json
Labels: Kvalitetssikring er gjennomført, Frist 12.01

#398 Doc: Lagt til sjekkDelutfall
  Doc/Testregelformat/Rutingreglar.md
Labels: documentation

#401 Oppdatert Interfaces og test
  Tests/format.test.ts
  src/interface/Delutfall.ts
  src/interface/Handling.ts
  src/interface/Regel.ts
  src/interface/RutingTriggere.ts
  src/interface/Steg.ts
  src/interface/Testregel.ts
Labels: documentation

#404 Splitta de ulike typene av steg for å gjøre det lettere å lese
  Tests/format.test.ts
  src/interface/Handling.ts
  src/interface/Steg.ts
Labels: Forbedring

#405 Bedre dokumentasjon - Interfaces
  src/interface/Delutfall.ts
  src/interface/Handling.ts
  src/interface/Regel.ts
  src/interface/RutingTriggere.ts
Labels: documentation

#406 Lagt til Utfall typer
  src/interface/Handling.ts
Labels: documentation

#407 Utvida for å kunne legge til fleire radioknappar
  Tests/format.test.ts
  src/interface/RutingTriggere.ts
Labels: Forbedring
