Repository TilsynForUniversellUtforming/testreglar-wcag-2.x, pull requests merged in 2024-02, with the labels that each got.

#411 Bug: Fiksa feil id-er og filnamn
  Testreglar/1.4.4/App/app-1.4.4a.json
  Testreglar/2.1.1/Nett/nett-2.1.1a.json
  Testreglar/2.1.2/Nett/nett-2.1.2a.json
  Tests/format.test.ts
  Utdatert/1.4.3/app-1.4.3a-2022.json
Labels: bug

#412 Fiksa bug i test
  Tests/format.test.ts
Labels: bug

#413 Retta feil i id - nett-3.1.1a og nett-3.1.2a
  Testreglar/3.1.1/Nett/nett-3.1.1a.json
  Testreglar/3.1.2/Nett/nett-3.1.2a.json
Labels: bug

#348 nett 1.3.1b er klar for ks
  Testreglar/1.3.1/Nett/nett-1.3.1b.json
Labels: Kvalitetssikring er gjennomført, Frist 26.01

#416 Bedre testdekning av delutfall
  Testreglar/1.2.1/1.2.1b.json
  Testreglar/2.2.1/Nett/2.2.1a.json
  Tests/format.test.ts
Labels: Forbedring

#350 app-1.3.1a er klar for ks
  Testreglar/1.3.1/App/app-1.3.1a.json
Labels: Klar for kvalitetssikring, Kvalitetssikring er gjennomført, Frist 26.01

#351 nett-1.3.1c er klar for ks
  Testreglar/1.3.1/Nett/nett-1.3.1c.json
Labels: Klar for kvalitetssikring, Kvalitetssikring er gjennomført, Frist 26.01

#353 app-1.3.1c er klar for ks
  Testreglar/1.3.1/App/app-1.3.1c.json
Labels: Kvalitetssikring er gjennomført, Frist 26.01

#374 nett-1.3.1e er klar for ks
  Testreglar/1.3.1/Nett/nett-1.3.1e.json
Labels: Kvalitetssikring er gjennomført, Frist 26.01

#354 nett-1.3.1d er klar for ks
  Testreglar/1.3.1/Nett/nett-1.3.1d.json
Labels: Kvalitetssikring er gjennomført, Frist 26.01

#422 Retta feil i interface for RegelTalDersom samt oppdatert tester for
  Tests/format.test.ts
  src/interface/Regel.ts
Labels: bug

#386 nett 3.3.4a er klar for ks
  Testreglar/3.3.4/Nett/nett-3.3.4a.json
Labels: Kvalitetssikring er gjennomført, Frist 02.02

#387 app-3.3.4a er klar for ks
  Testreglar/3.3.4/App/app-3.3.4a.json
Labels: Kvalitetssikring er gjennomført, Frist 02.02

#390 nett-3.3.4b er klar for ks
  Testreglar/3.3.4/Nett/nett-3.3.4b.json
Labels: Kvalitetssikring er gjennomført, Frist 02.02

#429 bump typescript-eslint to 7.0.1
  package-lock.json
  package.json
Labels: dependencies

#430 Oppdatert dokumentasjon
  Doc/Testregelformat/Testregelformat.md
Labels: documentation

#431 Update Testregelformat.md
  Doc/Testregelformat/Testregelformat.md
Labels: bug, documentation

#433 Fiksa type spec
  Tests/format.test.ts
  src/interface/Steg.ts
Labels: Forbedring

#434 Update Testregelformat.md
  Doc/Testregelformat/Testregelformat.md
Labels: documentation

#436 Fix i label action
  .github/workflows/label.yml
  Tests/format.test.ts
Labels: bug

#392 app-3.3.4b er klar for ks
  Testreglar/3.3.4/App/app-3.3.4b.json
Labels: Kvalitetssikring er gjennomført, Frist 02.02
